name: Nix Flake

on:
  push:
  pull_request:
jobs:
  test-flake:
    name: Test Flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check
    - run: nix flake metadata
  test-application:
    name: Test Application
    runs-on: ubuntu-latest
    needs: test-flake
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --command bash -c "go test"
  build:
    name: Build Application
    needs: [test-flake, test-application]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build

